# Generated by Django 4.0.5 on 2022-06-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=2)),
                ('y', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
