# Generated by Django 4.0.5 on 2022-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_xy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xy',
            name='x',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='xy',
            name='y',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
